const bcrypt = require('bcryptjs');
const { Pool, neonConfig } = require('@neondatabase/serverless');
const ws = require('ws');

// @neondatabase/serverless needs a WebSocket implementation on Node (only modern
// Node has a native global WebSocket) to support real multi-statement sessions —
// required for our BEGIN/COMMIT transaction shim, which the plain HTTP/fetch
// transport (neonConfig.poolQueryViaFetch) can't do.
neonConfig.webSocketConstructor = ws;

// Every concurrent serverless invocation gets its own module-scope pool, all
// sharing Neon's connection cap — keep each pool's footprint small and let idle
// connections close quickly instead of pinning them across warm containers.
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  max: 3,
  idleTimeoutMillis: 10000,
  connectionTimeoutMillis: 10000,
});

// Converts the `?`-style placeholders every route file already uses into
// Postgres's positional `$1, $2, ...` syntax. Safe here because no query in
// this codebase reuses one bind value twice, embeds a literal `?`, or uses LIKE.
function toPositional(sql) {
  let i = 0;
  return sql.replace(/\?/g, () => `$${++i}`);
}

// Mirrors the libSQL client call shape (`{ rows, rowsAffected, lastInsertRowid }`)
// so every route file's `db.execute({ sql, args })` keeps working unchanged.
// INSERTs that need `lastInsertRowid` must add `RETURNING id` themselves —
// Postgres has no automatic equivalent.
async function runQuery(executor, query) {
  const { sql, args } = typeof query === 'string' ? { sql: query, args: [] } : query;
  const result = await executor.query(toPositional(sql), args);
  return {
    rows: result.rows,
    rowsAffected: result.rowCount,
    lastInsertRowid: result.rows?.[0]?.id,
  };
}

const db = {
  execute: (query) => runQuery(pool, query),
  executeMultiple: (sql) => pool.query(sql),
  async transaction() {
    const client = await pool.connect();
    await client.query('BEGIN');
    return {
      execute: (query) => runQuery(client, query),
      commit: () => client.query('COMMIT'),
      rollback: async () => {
        try {
          await client.query('ROLLBACK');
        } catch {
          // The session may already be aborted by the error that triggered this
          // rollback — swallow so the original error is what callers see.
        }
      },
      close: () => client.release(),
    };
  },
};

const SCHEMA_SQL = `
  CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    full_name TEXT NOT NULL,
    role TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS customers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    alternate_phone TEXT DEFAULT '',
    address TEXT DEFAULT '',
    photo_path TEXT,
    registration_date TEXT NOT NULL,
    registration_time TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    notes TEXT DEFAULT '',
    is_deleted INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS equipment (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category_id INTEGER,
    daily_rent REAL NOT NULL DEFAULT 0,
    security_deposit REAL NOT NULL DEFAULT 0,
    current_status TEXT NOT NULL DEFAULT 'available',
    current_location TEXT DEFAULT '',
    image_path TEXT,
    notes TEXT DEFAULT '',
    is_deleted INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS rentals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number TEXT NOT NULL,
    customer_id INTEGER NOT NULL,
    equipment_id INTEGER NOT NULL,
    rental_date TEXT NOT NULL,
    rental_time TEXT NOT NULL,
    expected_return_date TEXT NOT NULL,
    expected_return_time TEXT NOT NULL,
    rental_days INTEGER NOT NULL DEFAULT 1,
    daily_rate REAL NOT NULL DEFAULT 0,
    deposit REAL NOT NULL DEFAULT 0,
    total_rent REAL NOT NULL DEFAULT 0,
    final_amount REAL NOT NULL DEFAULT 0,
    payment_status TEXT NOT NULL DEFAULT 'pending',
    rental_status TEXT NOT NULL DEFAULT 'active',
    created_by INTEGER,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS payments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_id INTEGER NOT NULL,
    amount REAL NOT NULL DEFAULT 0,
    payment_method TEXT NOT NULL DEFAULT 'cash',
    payment_type TEXT NOT NULL DEFAULT 'rent',
    payment_date TEXT NOT NULL,
    notes TEXT DEFAULT '',
    created_by INTEGER,
    created_at TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS shop_settings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name TEXT NOT NULL,
    shop_address TEXT NOT NULL,
    shop_phone TEXT NOT NULL,
    shop_email TEXT,
    shop_logo_path TEXT,
    invoice_prefix TEXT NOT NULL DEFAULT 'INV',
    currency_symbol TEXT NOT NULL DEFAULT '₹',
    updated_at TEXT NOT NULL
  );
`;

// Add columns to tables that pre-date this migration, one at a time (mirrors
// the old SQLite "no ADD COLUMN IF NOT EXISTS" guard, now checked via
// information_schema instead of PRAGMA table_info).
async function ensureColumn(table, column, definition) {
  const existing = await pool.query(
    'SELECT column_name FROM information_schema.columns WHERE table_name = $1 AND column_name = $2',
    [table, column],
  );
  if (!existing.rows.length) {
    await pool.query(`ALTER TABLE ${table} ADD COLUMN ${column} ${definition}`);
  }
}

async function ensureSeedData() {
  const existingAdmin = await db.execute({ sql: 'SELECT id FROM users WHERE username = ?', args: ['admin'] });
  if (!existingAdmin.rows.length) {
    const hash = bcrypt.hashSync('admin123', 10);
    await db.execute({
      sql: `INSERT INTO users (username, password_hash, full_name, role, is_active, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)`,
      args: ['admin', hash, 'System Administrator', 'owner', 1, new Date().toISOString(), new Date().toISOString()],
    });
  }

  const existingSettings = await db.execute('SELECT id FROM shop_settings WHERE id = 1');
  if (!existingSettings.rows.length) {
    await db.execute({
      sql: `INSERT INTO shop_settings (id, shop_name, shop_address, shop_phone, shop_email, shop_logo_path, invoice_prefix, currency_symbol, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      args: [1, 'Electrical Equipment Rentals', '123 Main Street, City', '+91 9876543210', null, null, 'INV', '₹', new Date().toISOString()],
    });
  }

  const defaultCategories = ['Generator', 'Drill Machine', 'Welding Machine', 'Compressor', 'Cutting Machine', 'Mixer', 'Vibrator', 'Other'];
  for (const name of defaultCategories) {
    const existing = await db.execute({ sql: 'SELECT id FROM categories WHERE name = ?', args: [name] });
    if (!existing.rows.length) {
      await db.execute({
        sql: 'INSERT INTO categories (name, description, is_active, created_at) VALUES (?, ?, ?, ?)',
        args: [name, null, 1, new Date().toISOString()],
      });
    }
  }
}

// Schema-only setup (no seeding) — exported separately so the one-off data
// migration script can create tables and migrate real rows into them *before*
// ensureSeedData() ever runs and inserts its own admin user / default rows.
async function ensureSchema() {
  try {
    await db.executeMultiple(SCHEMA_SQL);
  } catch (err) {
    // Concurrent cold starts on Vercel can race CREATE TABLE IF NOT EXISTS
    // against each other — Postgres's IF NOT EXISTS isn't fully race-safe, so
    // tolerate the "already exists" errors that race produces.
    if (err.code !== '42P07' && err.code !== '42710') {
      throw err;
    }
  }

  await ensureColumn('rentals', 'actual_return_date', 'TEXT');
  await ensureColumn('rentals', 'actual_return_time', 'TEXT');
  await ensureColumn('rentals', 'late_fee', 'REAL NOT NULL DEFAULT 0');
  await ensureColumn('rentals', 'damage_charge', 'REAL NOT NULL DEFAULT 0');
  await ensureColumn('rentals', 'refund_amount', 'REAL NOT NULL DEFAULT 0');
  await ensureColumn('rentals', 'return_notes', "TEXT DEFAULT ''");
  await ensureColumn('payments', 'discount', 'REAL NOT NULL DEFAULT 0');
  await ensureColumn('payments', 'invoice_number', 'TEXT');

  // One invoice can cover several equipment items (rentals rows). Payments settle
  // the whole invoice at once, so backfill invoice_number for any pre-existing
  // payment rows that only recorded a single rental_id.
  await db.execute(`
    UPDATE payments SET invoice_number = (SELECT invoice_number FROM rentals WHERE rentals.id = payments.rental_id)
    WHERE invoice_number IS NULL
  `);

  // Rentals resolve customers by phone number, so this lookup runs on every create/edit.
  await db.execute('CREATE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone_number)');
  await db.execute('CREATE INDEX IF NOT EXISTS idx_rentals_invoice ON rentals(invoice_number)');
  await db.execute('CREATE INDEX IF NOT EXISTS idx_payments_invoice ON payments(invoice_number)');
}

async function initialize() {
  await ensureSchema();
  await ensureSeedData();
}

// Memoized so schema/seed setup runs once per warm process (a warm serverless
// container on Vercel) instead of on every call.
let readyPromise = null;
function ready() {
  if (!readyPromise) {
    readyPromise = initialize();
  }
  return readyPromise;
}

module.exports = { db, ready, ensureSchema };
